### ISSUE TITLE
Good work

### ISSUE THREAD

**Issue by mbp** [Iamcerba/AspNetCore.CacheOutput#1]
Would be great if it was a nuget package you could consume. I understand you prefer if https://github.com/filipw/Strathweb.CacheOutput took in your changes, but maybe the best thing would be a completely separate library for ASP.NET Core.

Also, probably it should not be named WebApi.

**Comment by Iamcerba** [comment]
Hello, @mbp!

Thank you. I don't think it will be correct to create my own package, because I'm not original author. Also I didn't plan to support it for now :) 

From my point of view it will be better to push original author FilipW in [this](https://github.com/filipw/Strathweb.CacheOutput/issues/217) topic to at least receive his approval and until this moment use this code directly in solution.

> Also, probably it should not be named WebApi.

Did you mean something like WebApiCore?

**Comment by mbp** [comment]
I mean in ASP.NET Core there is no such thing as "Web API". It's all just ASP.NET Core MVC. So rather the name should be something like `AspNetCore.OutputCache`.

Would be great if @filipw took this on!

**Comment by Iamcerba** [comment]
@mbp, done.

**Comment by Iamcerba** [comment]
Hi, @mbp, 

I have published the [package](https://www.nuget.org/packages/AspNetCore.CacheOutput/).
